version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  gateway:
    depends_on:
      - app
    build: ./GateWay
    restart: on-failure
      # env_file: ./.env
    ports:
        - 7777:7777
  
  app:
    # depends_on:
    #   - mysqldb
    build: ./Eureka_Server
    restart: on-failure
    # env_file: ./.env
    ports:
      - "8761:8761"
    # environment:
    #   SPRING_APPLICATION_JSON: '{
    #     "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
    #     "spring.datasource.username" : "$MYSQLDB_USER",
    #     "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
    #     "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    #     "spring.jpa.hibernate.ddl-auto" : "update" }'
  client:
    depends_on:
        - mysqldb
        - app
    build: ./Client
    restart: on-failure
    env_file: ./.env
    ports:
        - "8088:8088"
    environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"}'     
    
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  voiture:
    depends_on:
      - mysqldb
      - app
      - client
    build: ./Voiture
    restart: on-failure
    env_file: ./.env
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE_2?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
          "spring.jpa.hibernate.ddl-auto" : "update"}'

    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: